services:
  mailer.dev.set_recipients:
    class: Symfony\Component\Mailer\EventListener\EnvelopeListener
    tags: ['kernel.event_subscriber']
    arguments:
      $sender: null
      $recipients: ['%env(DEFAULT_RECIPIENT)%']